import './bootstrap';
import HeaderFix from './headerFix';
import GetScreensize from './getScreensize';
import GetTimezone from './getTimezone';
import DropdownToggle from './dropdownToggle';
import SetSearching from './setSearching';
import ShowHidePassword from './showHidePassword';
import SetTimeNotifications from './SetTimeNotifications';
import MaskInputTel from './maskInputTel';
import BurgerButtonAndNavMobile from './burgerButtonAndNavMobile';
import Anchor from './anchor';
// import LinkTopPage from './linkTopPage';
import SelectReset from './selectReset';
import inputPricesVisible from './inputPricesVisible';
import RadioPageVisible from './radioPageVisible';
import SelectVisible from './selectVisible';
import MakeFormInCatalogsubmit from './makeFormInCatalogsubmit';
import DisableEnableButton from './disableEnableButton';
import BookmarkRemoving from './bookmarkRemoving';
import ShowHideMobileFilterBlock from './showHideMobileFilterBlock';
import LockOrientation from './lockOrientation';
import ResetButtonFilterMobile from './resetButtonFilterMobile';
import LoadingState from './loadingState';

